### ISSUE TITLE
3d data 

### ISSUE THREAD

**Issue by tonbing** [zohourih/rodinia_fpga#1]
Is there any of the opencl kernel file which you can direct me where I can find you are dealing with 3d data similar to convolution like functions ?

**Comment by zohourih** [comment]
If I understand your question correctly, you are looking for an OpenCL kernel which implements a 3D box stencil (a.k.a 3D convolution). I am afraid Rodinia does not provide such kernel as far as I know and I have never implemented one myself, either.

**Comment by tonbing** [comment]
OK got it. I just need some suggestion. I designed one 3d convolution module with single thread and ndrange, but I am getting better results with nd range mode. Which I believe is because of better interleaving done at run time from ndrange kernel.  But for single thread I have 3 nested loops. Is because of that number of nested loops , it is not performing well. Do you have any suggestions I can improve on interleaving of data ?

**Comment by zohourih** [comment]
The memory behavior in NDRange and Single Work-item is very similar. e.g. for coalescable accesses, a SIMD size of 8 in an NDRange kernel result in the same memory throughput as an unroll factor of 8 in its equivalent Single Work-item kernel (check this file as an example: https://github.com/zohourih/FPGAStream/blob/master/fpga-stream-kernel-std.cl).

Have you checked the II (Initiation Interval) of your nested loop in the Single Work-item kernel? If the II of all the loops is not one, the NDRange equivalent could potentially perform better due to dynamic run-time thread scheduling. Another source of difference could be in the degree of parallelism. If you are using SIMD in the NDRange kernel, you should also use the equivalent amount of loop unrolling on the Single Work-item one and make sure they are applied in the same direction so that the memory ports will be created in a similar fashion. Finally, sometimes the compiler decides to automatically unroll some loops and this decision does not necessarily always result in performance improvement; look for warnings about auto-unrolling in the compilation log to see this is not happening.

**Comment by tonbing** [comment]
Thanks for your reply. I think for my case problem is the problem of parallelism. For Ndrange I have used very similar pattern to shift register but although it not generated as shift register. But I have higher innermost loop , but for for single thread I am not able to unroll that innermost loop because if I do tool do not generate shift register. Also looking at the report generated I see that  I have initiation interval of 1 for all the loops. I am attaching my loop analysis of report generated, if you have any suggestions I will be happy to improve on that[
![results](https://user-images.githubusercontent.com/42953782/54859987-00fd8000-4cd1-11e9-941f-711341413e33.PNG)
](url)

**Comment by zohourih** [comment]
The loop report looks fine to me. Indeed it is not possible to infer shift registers in NDRange, that is a Single Work-item-only feature. The difference in performance, as you said, is likely the result of different degree of parallelism.

Inferring shift register could be tricky when coupled with unrolling. You should make sure your unrolled read/write size from/to the shift register is equal to the shifting size. You can find an example of unrolling with shift register here:

https://github.com/zohourih/rodinia_fpga/blob/master/opencl/hotspot3D/hotspot3D_kernel_v5.cl

That code is a 3D stencil and its computation would be very similar to 3D convolution with the exception that diagonal neighbor accesses are not included in the stencil. Adding those accesses requires minor modifications in the code.

**Comment by tonbing** [comment]
Thanks for your answer,  that examples helps . I have another question, so my innermost loop has fixed upper limit. So would increasing the innermost loop limit so that it decreases outermost loop limit, does that help in improving performance?

**Comment by zohourih** [comment]
It depends. For Single Work-item if all the loop nest is pipelined with an II of one, then the loop trip counts will not have much of an effect on performance. However it sometimes happens that in a loop nest, the II of the outer loops is increase to 2 by the compiler to prevent low operating frequency. In such cases it is best to maximize the trip count of the innermost loop that has an II of one.

For NDRange, it is best to avoid loops altogether. If you can decrease loop trip count in an NDRange kernel and instead increase the local work-group size, then that could result in higher performance since loops are not pipelined in such kernels but work-items are.

**Comment by tonbing** [comment]
I see your point,  my outer loop let's say runs for 20 times so those 20 times are totally independent of each other so I am using #Pragma ivdep to indicate that, but all the data initialization of shift register is in my innermost loop, so I do not think so any pipelining is happening between my outer and inner loops ,  Could that also be the factor impacting the performance ?

**Comment by zohourih** [comment]
If some loops in the loop nest cannot be pipelined with respect to each other, the compiler will clearly indicate this. E.g. the report would say that the loop is not pipelined at all, or it is pipelined but it runs serially over its inner loop (which essentially means it is not pipelined if you have a perfect loop nest). I do not see any such message in the snippet you posted from the report, so I would assume all the loop nest is pipelined. However, you should carefully check the bottom of the report for every loop in the report to make sure such message does not exist.

P.S. #pragma ivdep only affects load/store memory dependencies; it has no effect on loop-carried dependencies.

**Comment by tonbing** [comment]
Thanks for your answers. I am able to go in right direction. To improve further I have divided my function into 3 kernel with memory read, computation and then memory write. I was hoping it to pipeline the data and increase throughput by that factor but when I try to measure time using profiler I donot see such improvement. According to the results which I am getting it's like all memory read , computation and memory writing are happening in parallel and they wait for writing to memory then start execution for the next set of data. I believe something I am doing wrong from the host side. Can you please suggest some improvement which I can do to improve the results.
![results](https://user-images.githubusercontent.com/42953782/55055826-75ae2280-5021-11e9-952a-2c2e7809a67c.PNG)

**Comment by zohourih** [comment]
It seems to me that for the second round of execution, the memrd kernel is starting and also finishing slightly faster than the the other two kernels, closely followed by the conv kernel, and memwrite starts last and finishes last. Do you expect something else? If you are talking about the gap between the first memwrite and the second memrd, that could very will be profiling overhead or kernel launch overhead.

I am not sure how your host code is constructed, though. What I would do is that I would convert the conv kernel to autorun, and have two queues, one for read and one for write, and keep queuing the iterations one after another and use an OpenCL event from memwrite enqueue in the next memread enqueue for synchronization.

**Comment by tonbing** [comment]
No, sorry about not adding the execution time. I have added below, both rounds have similar execution time. 
![results](https://user-images.githubusercontent.com/42953782/55059883-5c12d800-502d-11e9-8ddf-49b6755149e4.PNG)

My host structure is like that  for let's say 2 image
while( i<2)
{
mem read ,
conv, 
mem write
} , and each memread I am sending the entire image. 
What I expected to have was something like how normal pipeline should have worked. Like mem read finishing earlier than conv which finishes earlier than mem read. In the meantime when memwrite is still writing the result of image 1, memread should have started reading for image2, like in a pipeline way which I am not seeing. That's what is confusing to me. 
So I checked my profiler results, I am having 30% stall rate when I reading from memory and 50% when reading from the channel from memread to conv kernel. Could that be the reason for all 3 kernel taking same execution time ?

**Comment by zohourih** [comment]
If your application is memory-bound, then the conv kernel will stall waiting for memory read, and the memory write kernel will stall waiting for conv; essentially, memory read stalls propagate all the way down the pipeline. That would explain why the run time of the kernels is roughly the same.

**Comment by tonbing** [comment]
First of all, I would really like to thank you. I am getting good support from you, otherwise, I am working on this problem for a while but because there are not enough sources available I am struggling a lot. 

I removed that memory stall rate by changing the index, so I was able to reduce memory read stall rate, but still for one of the channels reading, I got like 31% of the stall, but even with that I do not see any pipeline effect basically.  
So, I guess I suspect there are 2 reasons for that I am not able to see the pipeline impact, 
1. One could be like as you mentioned memory bound, like most of the time I am doing memory operation, **do you have any suggestions on how to improve on this factor?**
2. Could it somehow be because of the profiler, that is first samples the events till all functions are completed for one dataset then after that only it does sampling for other datasets?

**Comment by zohourih** [comment]
One advice I would give you is to **not** rely on the values reported by the profiler too much. The profiler has a certain level of accuracy and correctly interpreting its reports is difficult.

If you zoom into the image you posted using photoshop, or zoom into the profiler, it indeed seems that the mem read kernel is starting like one pixel sooner than the other two, and mem write is finishing one pixel later than the other two. So, it seems there is a very small pipelining effect but since the difference is small, it is very difficult to see. And, to be honest, this is expected. You should never expect to be compute-bound on a deep-pipelined FPGA design, unless your design does not fit on the device. If it does fit, then it will be memory-bound and most pipeline stalls will be because of memory stalls.

Regarding memory bandwidth, you can take a look at the following threads on Intel's forum where I have talked about how one can improve the memory bandwidth (user names where lost during transition from Altera to Intel, though):

https://forums.intel.com/s/question/0D50P00003yyTckSAE/loopunrolling-and-memory-access-performance?language=en_US
https://forums.intel.com/s/question/0D50P00003yyTK3SAM/global-memory-access-512-bit-width-constrain?language=en_US

Regarding the profiler, from what I know, it dumps profiled data after each kernel execution, and this itself could cause execution overhead. Furthermore, kernels compiled with profiling enabled tend to have lower operating frequency than normal, which reduces their performance compared to the normal case.

**Comment by tonbing** [comment]
If you can, 
can you reply to my questions on Intel forums 
https://forums.intel.com/s/question/0D70P000006FqGiSAK

Thanks

**Comment by zohourih** [comment]
Let's continue the discussion on the forum, then.

**Comment by zohourih** [comment]
I already replied to both of your threads on the forum. I also closed the issue on Github already; I guess that is why this new reply you sent is not showing up on Github. Anyway, I will reply directly from email.

DDR memory has a fixed bandwidth. This bandwidth is shared between reading and writing. It is not like network or PCI-E that is full-duplex. Essentially, with each bank of DDR memory, you can transfer a total of 512 bits per kernel clock (read+write) and if your kernel is running at 266 MHz or more (on Arria 10 with DDR4 memory), this will nearly saturate the memory bandwidth. Your board only has one memory back, so you are limited to a total of 512 bits per clock for reading AND writing, rather than 512 bits for each. You are doing a lot more than that though. You are reading one float16 and writing twelve float16 (excluding the mask). You should note that the compiler is coalescing your writes inside of the innermost loop to 512-bit accesses, and you are also unrolling the y loop on top of that, which creates twelve 512-bit writes. This is far too much for one memory bank.

-----Original message-----

**Comment by tonbing** [comment]
Thanks for your reply. This was my mistake to add any comment to the closed
github issue, and So I deleted that instantly , because I have asked
similar question on Intel forum where you have replied and I have made
changes based on the suggestion suggested.  If I have other doubt I will
post that on Intel forum only.

Thanks
Akshay

**Comment by zohourih** [comment]
Okay, good luck. 😄
